// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisLabZetino.Infrastructure.Data;

#nullable disable

namespace SisLabZetino.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251017190809_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SisLabZetino.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcita");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime")
                        .HasColumnName("fechahora");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idusuario");

                    b.HasKey("IdCita");

                    b.ToTable("t_Cita", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.Examen", b =>
                {
                    b.Property<int>("IdExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idexamen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdExamen"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<int>("IdOrdenExamen")
                        .HasColumnType("int")
                        .HasColumnName("idordenexamen");

                    b.Property<int>("IdTipoExamen")
                        .HasColumnType("int")
                        .HasColumnName("idtipoexamen");

                    b.Property<int>("TiempoEstimado")
                        .HasColumnType("int")
                        .HasColumnName("tiempoestimado");

                    b.HasKey("IdExamen");

                    b.ToTable("t_Examen", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.Muestra", b =>
                {
                    b.Property<int>("IdMuestra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idmuestra");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMuestra"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("date")
                        .HasColumnName("fecharecepcion");

                    b.Property<int>("IdOrdenExamen")
                        .HasColumnType("int")
                        .HasColumnName("idordenexamen");

                    b.Property<int>("IdTipoMuestra")
                        .HasColumnType("int")
                        .HasColumnName("idtipomuestra");

                    b.HasKey("IdMuestra");

                    b.ToTable("t_Muestra", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.NotificacionEmail", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idnotificacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("asunto");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estadoenvio");

                    b.Property<int>("IdResultado")
                        .HasColumnType("int")
                        .HasColumnName("idresultado");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("mensaje");

                    b.HasKey("IdNotificacion");

                    b.ToTable("t_notificacionEmail", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.OrdenExamen", b =>
                {
                    b.Property<int>("IdOrdenExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idordenexamen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOrdenExamen"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("date")
                        .HasColumnName("fechasolicitud");

                    b.Property<int>("IdCita")
                        .HasColumnType("int")
                        .HasColumnName("idcita");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idusuario");

                    b.HasKey("IdOrdenExamen");

                    b.ToTable("t_ordenExamen", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.Resultado", b =>
                {
                    b.Property<int>("IdResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idresultado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdResultado"));

                    b.Property<string>("ArchivoResultado")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("archivoresultado");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fechaentrega");

                    b.Property<int>("IdExamen")
                        .HasColumnType("int")
                        .HasColumnName("idexamen");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdResultado");

                    b.ToTable("t_Resultado", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idrol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.ToTable("t_rol", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.TipoExamen", b =>
                {
                    b.Property<int>("IdTipoExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtipoexamen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoExamen"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio");

                    b.HasKey("IdTipoExamen");

                    b.ToTable("t_TipoExamen", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.TipoMuestra", b =>
                {
                    b.Property<int>("IdTipoMuestra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtipomuestra");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoMuestra"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoMuestra");

                    b.ToTable("t_TipoMuestra", (string)null);
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idusuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fechanacimiento");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("idrol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("telefono");

                    b.Property<int?>("idrol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("idrol");

                    b.ToTable("t_usuariosistema", null, t =>
                        {
                            t.Property("idrol")
                                .HasColumnName("idrol1");
                        });
                });

            modelBuilder.Entity("SisLabZetino.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SisLabZetino.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("idrol");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
